### ISSUE TITLE
Problem with scroll mode

### ISSUE THREAD

**Issue by visualcookie** [Cimplex/SpotifyScraper#2]
Hi,

in scroll mode under OBS the Artist and Song stick together like the following:
"Future World Music - The Devil's WaltzFuture World Music - The Devil's Waltz"

**Comment by Cimplex** [comment]
I never used scrolling before. I see several ways to fix it. I will probably just add static spaces after the title-artist when the user turns on a "scrolling capability mode," Until I finish the text parsing stuff, which will allow much more customization, its the simplist thing I can do.

**Comment by Cimplex** [comment]
Let me know if you have any other issues. Will do my best to address them :+1:
